
#ifndef MAKESHIFT_VERSION_HPP_
#define MAKESHIFT_VERSION_HPP_

#define MAKESHIFT_VERSION_MAJOR 1
#define MAKESHIFT_VERSION_MINOR 0
#define MAKESHIFT_VERSION_PATCH 0

#define MAKESHIFT_VERSION_API 1

#endif // MAKESHIFT_VERSION_HPP_
